#!/usr/bin/env bash
# pi-shuttle __RELEASE_VERSION__ — official release installer bootstrap.
#
# Generated by scripts/build-release.mjs from the exact v0.1.0 release
# assets. Version-specific and self-verifying: the SHA-256 digests below
# are computed from the frozen release bytes and are the INTEGRITY root
# for the downloaded assets (host-selected release envelope + common
# pi-shuttle package).
# They do NOT authenticate this install.sh file itself: the authenticity
# of install.sh is rooted in HTTPS/TLS + GitHub + this explicitly
# version-specific release URL. Do not edit this file; a digest mismatch
# here means the file is not the official release installer.
#
# Trust chain:
#   install.sh (authenticity: HTTPS + GitHub + version-pinned URL)
#     └─ embeds both envelope digests + PI_SHUTTLE_TGZ_SHA256
#     └─ derives the real Node host and downloads + verifies the matching
#        Linux/shared-macOS envelope and pi-shuttle-<v>.tgz
#     └─ runs the verified pi-shuttle installer in release mode, which
#        validates the envelope (closed schema, exact source pins) and
#        downloads/verifies the Gateway and pi-guard artifacts before
#        the existing install core activates anything.
set -euo pipefail

die() { printf 'pi-shuttle-installer: %s\n' "$*" >&2; exit 2; }

RELEASE_VERSION="__RELEASE_VERSION__"
LINUX_ENVELOPE_SHA256="__LINUX_ENVELOPE_SHA256__"
MACOS_ENVELOPE_SHA256="__MACOS_ENVELOPE_SHA256__"
PI_SHUTTLE_TGZ_SHA256="__PI_SHUTTLE_TGZ_SHA256__"
RELEASE_BASE_URL="https://github.com/mfx-labs/pi-shuttle/releases/download/v${RELEASE_VERSION}"
# QA/test override only: production installs never set this. The value is
# validated as an https:// URL below so it can never be interpreted as a
# downloader option (F-07); the fetch function also enforces HTTPS-only
# at every hop regardless.
if [ -n "${PI_SHUTTLE_BASE_URL:-}" ]; then
  case "$PI_SHUTTLE_BASE_URL" in
    https://*) RELEASE_BASE_URL="$PI_SHUTTLE_BASE_URL" ;;
    *) die 'PI_SHUTTLE_BASE_URL (QA override) must be an https:// URL' ;;
  esac
fi

die() { printf 'pi-shuttle-installer: %s\n' "$*" >&2; exit 2; }

die() { printf 'pi-shuttle-installer: %s\n' "$*" >&2; exit 2; }

for arg in "$@"; do
  case "$arg" in
    --help|-h)
      cat <<'EOF'
usage: curl -fsSL <versioned-installer-url> | bash [installer options]

Installer options (forwarded to the pi-shuttle installer):
  --batch                        non-interactive; component selections are required
  --gateway <yes|no>             install Project Gateway MCP (default yes when interactive)
  --pi-guard <yes|no>            install pi-guard (default yes when interactive)
  --install-dir <path>           installation directory (default ~/.local/share/pi-shuttle)
  --bin-dir <path>               command/bin directory (default ~/.local/bin)

Interactive prompts read from your terminal, even when the installer
script itself is piped. In non-interactive environments (no terminal)
pass explicit selections, e.g.: --batch --gateway yes --pi-guard yes.

The official release installer manages artifact download and digest
verification internally; --artifact-dir and --expect-*-sha256 are local
artifact-lane options and are refused here.
EOF
      exit 0 ;;
    --artifact-dir|--expect-gateway-sha256|--expect-pi-guard-sha256)
      die "option '$arg' is not accepted by the official release installer (artifact acquisition is verified internally); use the local artifact lane from a source checkout for custom artifacts" ;;
    --batch) HAS_BATCH=1 ;;
    --gateway) HAS_GATEWAY=1 ;;
    --pi-guard) HAS_PI_GUARD=1 ;;
  esac
done

if [ "$(id -u)" = "0" ] 2>/dev/null; then
  die 'refusing to run as root: pi-shuttle installs per-user only'
fi
command -v node >/dev/null 2>&1 || die 'node not found on PATH (Node >= 22.19.0 is required)'
command -v tar >/dev/null 2>&1 || die 'tar not found on PATH'
command -v shasum >/dev/null 2>&1 || die 'shasum not found on PATH'

# Select only from real Node host facts, matching the product's own
# process.platform/process.arch target derivation. This is internal release
# routing, never a user-supplied architecture or target selector.
HOST_KEY="$(node -p 'process.platform + ":" + process.arch')" || die 'could not derive host platform/architecture from Node'
case "$HOST_KEY" in
  linux:x64)
    ENVELOPE_FILE="pi-shuttle-${RELEASE_VERSION}-linux-x86_64.json"
    ENVELOPE_SHA256="$LINUX_ENVELOPE_SHA256" ;;
  darwin:x64|darwin:arm64)
    ENVELOPE_FILE="pi-shuttle-${RELEASE_VERSION}-macos.json"
    ENVELOPE_SHA256="$MACOS_ENVELOPE_SHA256" ;;
  *)
    die "unsupported platform/architecture: $HOST_KEY (no release-envelope fallback)" ;;
esac

if command -v curl >/dev/null 2>&1; then
  # HTTPS-only at every hop (--proto applies to redirects too), bounded
  # redirects; --url takes the URL as DATA (never option syntax, F-07).
  fetch() { curl -fsSL --proto '=https' --tlsv1.2 --max-redirs 5 --url "$1" -o "$2"; }
elif command -v wget >/dev/null 2>&1; then
  # wget has no --url operand form; the PI_SHUTTLE_BASE_URL https://
  # validation above guarantees the URL can never start with '-'
  # (F-07).
  fetch() { wget -q --https-only --max-redirect=5 -O "$2" "$1"; }
else
  die 'curl or wget is required for release installation'
fi

# F-01: never let EOF on a pipe stand in for interactive answers. When
# interactive prompts will be needed (no explicit selections) and stdin
# is not a terminal (e.g. `curl ... | bash`), bind the installer's stdin
# to the controlling terminal if one exists; otherwise fail closed with
# guidance instead of silently defaulting.
NEEDS_PROMPTS=1
if [ "${HAS_BATCH:-0}" = "1" ] || { [ "${HAS_GATEWAY:-0}" = "1" ] && [ "${HAS_PI_GUARD:-0}" = "1" ]; }; then
  NEEDS_PROMPTS=0
fi
if [ "$NEEDS_PROMPTS" = "1" ] && [ ! -t 0 ]; then
  if exec 3<>/dev/tty 2>/dev/null; then
    exec 3<&-
    exec 3>&-
    NODE_STDIN_TTY=1
  else
    die 'no interactive terminal available: piped or non-interactive installs must pass explicit selections, e.g. --batch --gateway yes --pi-guard no'
  fi
else
  NODE_STDIN_TTY=0
fi

WORK="$(mktemp -d "${TMPDIR:-/tmp}/pi-shuttle-release.XXXXXX")"
trap 'rm -rf "$WORK"' EXIT

ENVELOPE="$WORK/$ENVELOPE_FILE"
PKG_TGZ="$WORK/pi-shuttle-${RELEASE_VERSION}.tgz"

printf 'pi-shuttle-installer: downloading release v%s assets\n' "$RELEASE_VERSION"
fetch "$RELEASE_BASE_URL/$ENVELOPE_FILE" "$ENVELOPE"
if [ "$(shasum -a 256 "$ENVELOPE" | awk '{print $1}')" != "$ENVELOPE_SHA256" ]; then
  die 'release envelope digest mismatch — refusing to continue (nothing was installed)'
fi
fetch "$RELEASE_BASE_URL/pi-shuttle-${RELEASE_VERSION}.tgz" "$PKG_TGZ"
if [ "$(shasum -a 256 "$PKG_TGZ" | awk '{print $1}')" != "$PI_SHUTTLE_TGZ_SHA256" ]; then
  die 'pi-shuttle package digest mismatch — refusing to continue (nothing was installed)'
fi

mkdir -p "$WORK/pkg"
tar -xzf "$PKG_TGZ" -C "$WORK/pkg"
if [ -f "$WORK/pkg/package/dist/installer/release/bootstrap.js" ]; then
  CORE="$WORK/pkg/package/dist/installer/release/bootstrap.js"
else
  die 'release package is missing the installer entry point'
fi

export PI_SHUTTLE_RELEASE_ENVELOPE="$ENVELOPE"
export PI_SHUTTLE_PI_SHUTTLE_TGZ="$PKG_TGZ"
export PI_SHUTTLE_RELEASE_TMP="$WORK"
# Run the installer as the last command (no exec): the EXIT trap above must
# fire after the installer exits so the verified release bytes never linger.
# With a piped script and a usable controlling terminal, the installer's
# prompts read from that terminal (F-01); otherwise stdin is inherited
# (already interactive, or explicit selections make prompting unnecessary).
if [ "$NODE_STDIN_TTY" = "1" ]; then
  node "$CORE" "$@" </dev/tty
else
  node "$CORE" "$@"
fi
