#!/usr/bin/env bash
# pi-shuttle __RELEASE_VERSION__ — official release installer bootstrap (manifest-native).
#
# Generated by scripts/build-release.mjs from the exact __RELEASE_VERSION__
# release assets. Version-specific and self-verifying: the SHA-256 digest
# below is computed from the frozen pi-shuttle package bytes and is the
# INTEGRITY root for that download.
#
# It does NOT authenticate this install.sh file itself: the authenticity of
# install.sh is rooted in HTTPS/TLS + GitHub + this explicitly
# version-specific release URL. Do not edit this file; a digest mismatch
# here means the file is not the official release installer.
#
# Gateway release authority is NOT carried here. The manifest-native
# installer (dist/installer/main.js) downloads and cryptographically
# verifies the SIGNED Gateway metadata chain (keyring -> stable channel ->
# Gateway release manifest) and the Gateway artifact from the compiled
# trusted origin at install time. This script carries no Gateway version,
# commit, releaseId, artifact digest, or artifact filename, and bundles no
# Gateway artifacts.
#
# pi-guard is independently managed and is NOT part of this installer.
set -euo pipefail

die() { printf 'pi-shuttle-installer: %s\n' "$*" >&2; exit 2; }

RELEASE_VERSION="__RELEASE_VERSION__"
PI_SHUTTLE_TGZ_SHA256="__PI_SHUTTLE_TGZ_SHA256__"
RELEASE_BASE_URL="https://github.com/mfx-labs/pi-shuttle/releases/download/v${RELEASE_VERSION}"
# QA/test override only: production installs never set this. The value is
# validated as an https:// URL below so it can never be interpreted as a
# downloader option (F-07); the fetch function also enforces HTTPS-only
# at every hop regardless.
if [ -n "${PI_SHUTTLE_BASE_URL:-}" ]; then
  case "$PI_SHUTTLE_BASE_URL" in
    https://*) RELEASE_BASE_URL="$PI_SHUTTLE_BASE_URL" ;;
    *) die 'PI_SHUTTLE_BASE_URL (QA override) must be an https:// URL' ;;
  esac
fi

for arg in "$@"; do
  case "$arg" in
    --help|-h)
      cat <<'EOF'
usage: curl -fsSL <versioned-installer-url> | bash

Installs the signed stable Gateway release through the manifest-native trust
chain: compiled trust policy -> signed keyring -> signed stable channel ->
signed Gateway release manifest -> verified artifact -> content-addressed
package -> signed cache -> Receipt Schema 1.

The installer accepts no component selections, no installation paths, no
release options, and no caller-selected release authority. The Gateway
signed metadata and artifact are downloaded and cryptographically verified
from the trusted release origin at install time. pi-guard is independently
managed and is not part of this installer.
EOF
      exit 0 ;;
    *)
      die "unrecognized installer option '$arg': the manifest-native installer accepts no selections, paths, or release options (pass --help for usage)" ;;
  esac
done

if [ "$(id -u)" = "0" ] 2>/dev/null; then
  die 'refusing to run as root: pi-shuttle installs per-user only'
fi
command -v node >/dev/null 2>&1 || die 'node not found on PATH (Node >= 22.19.0 is required)'
command -v tar >/dev/null 2>&1 || die 'tar not found on PATH'
command -v shasum >/dev/null 2>&1 || die 'shasum not found on PATH'

if command -v curl >/dev/null 2>&1; then
  # HTTPS-only at every hop (--proto applies to redirects too), bounded
  # redirects; --url takes the URL as DATA (never option syntax, F-07).
  fetch() { curl -fsSL --proto '=https' --tlsv1.2 --max-redirs 5 --url "$1" -o "$2"; }
elif command -v wget >/dev/null 2>&1; then
  # wget has no --url operand form; the PI_SHUTTLE_BASE_URL https://
  # validation above guarantees the URL can never start with '-'
  # (F-07).
  fetch() { wget -q --https-only --max-redirect=5 -O "$2" "$1"; }
else
  die 'curl or wget is required for release installation'
fi

WORK="$(mktemp -d "${TMPDIR:-/tmp}/pi-shuttle-release.XXXXXX")"
trap 'rm -rf "$WORK"' EXIT

PKG_TGZ="$WORK/pi-shuttle-${RELEASE_VERSION}.tgz"

printf 'pi-shuttle-installer: downloading release v%s pi-shuttle package\n' "$RELEASE_VERSION"
fetch "$RELEASE_BASE_URL/pi-shuttle-${RELEASE_VERSION}.tgz" "$PKG_TGZ"
if [ "$(shasum -a 256 "$PKG_TGZ" | awk '{print $1}')" != "$PI_SHUTTLE_TGZ_SHA256" ]; then
  die 'pi-shuttle package digest mismatch — refusing to continue (nothing was installed)'
fi

mkdir -p "$WORK/pkg"
tar -xzf "$PKG_TGZ" -C "$WORK/pkg"
CORE="$WORK/pkg/package/dist/installer/main.js"
if [ ! -f "$CORE" ]; then
  die 'release package is missing the manifest-native installer entry (dist/installer/main.js)'
fi

# Run the manifest-native installer (no exec: the EXIT trap above must fire
# after the installer exits so the verified release bytes never linger).
# The installer performs the signed Gateway selection and installation; it
# is non-interactive and accepts no authority arguments.
node "$CORE"
